name: Build Plugin Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build Application
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
    - name: Checkout all the submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Create Source-Code Zip
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r "Source Code.zip" Echosync
        
    - uses: bbonkr/get-version-action@v1
      id: get_version
      with:
          project: 'Echosync/Echosync.csproj'
          show_log_message: true
        
    - name: Setup dotnet v${{steps.get_version.outputs.version}}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Restore dependencies v${{steps.get_version.outputs.version}}
      run: dotnet restore "Echosync/Echosync.csproj"
      
    - name: Build v${{steps.get_version.outputs.version}}
      run: dotnet build /p:EnableWindowsTargeting=true --no-restore
      
    - name: Test v${{steps.get_version.outputs.version}}
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish v${{steps.get_version.outputs.version}}
      run: dotnet publish "Echosync/Echosync.csproj" -c Release -o release --nologo
      
    - name: Zip build v${{steps.get_version.outputs.version}}
      run: zip -r Echosync.zip Echosync/release/

    - uses: ncipollo/release-action@v1
      with:
          tag: ${{steps.get_version.outputs.version}}
          name: Echosync v${{steps.get_version.outputs.version}}
          artifacts: "Source Code.zip,Echosync.zip"
          bodyFile: "Echosync/Changelog.md"
