# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Plugin Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build Application
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
    - name: Checkout all the submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Create Source-Code Zip
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r "Source Code.zip" Echosync
        
    - name: Get version
      id: package_version
      uses: KageKirin/get-csproj-version@v1.0.0
      with:
          regex: "(\\d+)\.(\\d+)\.(\\d+)\.(\\d+)"
          file: "Echosync/Echosync.csproj"
        
    - name: Setup dotnet v${{steps.package_version.outputs.version}}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Restore dependencies v${{steps.package_version.outputs.version}}
      run: dotnet restore
      
    - name: Build v${{steps.package_version.outputs.version}}
      run: dotnet build /p:EnableWindowsTargeting=true --no-restore
      
    - name: Test v${{steps.package_version.outputs.version}}
      run: dotnet test --no-build --verbosity normal
      
    - name: Publish v${{steps.package_version.outputs.version}}
      run: dotnet publish "Echosync/Echosync.csproj" -c Release -o release --nologo
      
    - name: Zip build v${{steps.package_version.outputs.version}}
      run: zip -r Echosync.zip Echosync/release/

    - uses: ncipollo/release-action@v1
      with:
          tag: ${{steps.package_version.outputs.version}}
          name: Echosync v${{steps.package_version.outputs.version}}
          artifacts: "Source Code.zip,Echosync.zip"
          bodyFile: "Echosync/Changelog.md"
